//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreQue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreQue()
        {
            this.StoreQueOrders = new HashSet<StoreQueOrder>();
        }
    
        public int Id { get; set; }
        public int StoreDetailId { get; set; }
        public string StationDesc { get; set; }
    
        public virtual StoreDetail StoreDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreQueOrder> StoreQueOrders { get; set; }
    }
}
