//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreQueOrder
    {
        public int Id { get; set; }
        public int StoreQueId { get; set; }
        public string Customer { get; set; }
        public System.DateTime DtOrder { get; set; }
        public int CartDetailId { get; set; }
    
        public virtual StoreQue StoreQue { get; set; }
        public virtual CartDetail CartDetail { get; set; }
    }
}
